// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgyUu2T0qODPInVo5FxL93BfE-hCab5I',
    appId: '1:883041122970:android:8ec88080a2be2b27b9fd23',
    messagingSenderId: '883041122970',
    projectId: 'shelfaware-40125789',
    storageBucket: 'shelfaware-40125789.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6exqSKhLfPzl0dpQt7SzicMZDFPsIBGo',
    appId: '1:883041122970:web:f1bf683d50ec217db9fd23',
    messagingSenderId: '883041122970',
    projectId: 'shelfaware-40125789',
    authDomain: 'shelfaware-40125789.firebaseapp.com',
    storageBucket: 'shelfaware-40125789.firebasestorage.app',
    measurementId: 'G-36RWQ36PZS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNg8hpPDqztCSbbPXiYxcpSsl7fMdR7s',
    appId: '1:883041122970:ios:85070a44e1306df5b9fd23',
    messagingSenderId: '883041122970',
    projectId: 'shelfaware-40125789',
    storageBucket: 'shelfaware-40125789.firebasestorage.app',
    androidClientId: '883041122970-78qrad807vcav03e901l8ffk889seesn.apps.googleusercontent.com',
    iosClientId: '883041122970-hllk5jk646v6hdkis4de8rjjem4efgr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shelfawareApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNg8hpPDqztCSbbPXiYxcpSsl7fMdR7s',
    appId: '1:883041122970:ios:85070a44e1306df5b9fd23',
    messagingSenderId: '883041122970',
    projectId: 'shelfaware-40125789',
    storageBucket: 'shelfaware-40125789.firebasestorage.app',
    androidClientId: '883041122970-78qrad807vcav03e901l8ffk889seesn.apps.googleusercontent.com',
    iosClientId: '883041122970-hllk5jk646v6hdkis4de8rjjem4efgr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.shelfawareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6exqSKhLfPzl0dpQt7SzicMZDFPsIBGo',
    appId: '1:883041122970:web:6c3e1db57a2f7ad7b9fd23',
    messagingSenderId: '883041122970',
    projectId: 'shelfaware-40125789',
    authDomain: 'shelfaware-40125789.firebaseapp.com',
    storageBucket: 'shelfaware-40125789.firebasestorage.app',
    measurementId: 'G-D59MVPFCPT',
  );

}